### ISSUE TITLE
easy usage not responding

### ISSUE THREAD

**Issue by subomi** [unicodeveloper/nexmo-webtask#1]
tried the easy usage link as such
https://webtask.it.auth0.com/api/run/wt-prosperotemuyiwa-gmail_com-0/sms?phoneno=08077886076&message=what!

that number 08077886076 is my number but it does not work. Tried this as well: 
https://webtask.it.auth0.com/api/run/wt-prosperotemuyiwa-gmail_com-0/sms?phoneno=+2348077886076&message=what!

What am I doing wrongly boss?

**Comment by unicodeveloper** [comment]
Lol, I used my own nexmo account and I have run out of free credits, i guess that's why you aren't receiving any message. Try using this https://github.com/unicodeveloper/jusibe-webtask . I have a lot of free credits here

**Comment by subomi** [comment]
Lol. that worked! ... is jusibe indigenous tech like paystack?

**Comment by unicodeveloper** [comment]
Yes, it is, you should totally use it, so cool...there is a simple and easy PHP library i built for them https://github.com/unicodeveloper/jusibe-php-lib . There are other libraries on their doc page too https://jusibe.com/docs/

**Comment by subomi** [comment]
nice ... gone through the docs already. Would definitely use it boss. Thanks!
